<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_checkout_tests.TestDeliverProduct-20240424223209" tests="7" file="test_checkout_tests.py" time="0.051" timestamp="2024-04-24T22:32:10" failures="0" errors="2" skipped="0">
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_checkin_code_not_found_date_signature" time="0.005" timestamp="2024-04-24T22:32:10"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_bad_date_signature" time="0.004" timestamp="2024-04-24T22:32:10"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_no_date" time="0.005" timestamp="2024-04-24T22:32:10"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_no_store_check_in" time="0.005" timestamp="2024-04-24T22:32:10"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_store_check_in_is_empty" time="0.008" timestamp="2024-04-24T22:32:10"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_already_checkout" time="0.019" timestamp="2024-04-24T22:32:10">
		<error type="AttributeError" message="'dict' object has no attribute '__dict__'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/venv/lib/python3.10/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 75, in test_already_checkout
    value = my_manager.guest_checkout(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 207, in guest_checkout
    json_checkout_store.add_item(room_checkout)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/checkout_json_store.py", line 24, in add_item
    super().add_item(item)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/json_store.py", line 23, in add_item
    self.data_list.append(item.__dict__)
AttributeError: 'dict' object has no attribute '__dict__'
]]></error>
	</testcase>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_checkout_ok" time="0.005" timestamp="2024-04-24T22:32:10">
		<error type="AttributeError" message="'dict' object has no attribute '__dict__'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/venv/lib/python3.10/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 55, in test_checkout_ok
    value = my_manager.guest_checkout(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 207, in guest_checkout
    json_checkout_store.add_item(room_checkout)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/checkout_json_store.py", line 24, in add_item
    super().add_item(item)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/storage/json_store.py", line 23, in add_item
    self.data_list.append(item.__dict__)
AttributeError: 'dict' object has no attribute '__dict__'
]]></error>
	</testcase>
</testsuite>
