<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_room_reservation_tests.TestHotelReservation-20240425144236" tests="18" file="test_room_reservation_tests.py" time="0.072" timestamp="2024-04-25T14:42:37" failures="0" errors="18" skipped="0">
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_duplicated_id_reservation_tests" time="0.001" timestamp="2024-04-25T14:42:37">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 98, in test_duplicated_id_reservation_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_duplicated_reservation_tests" time="0.003" timestamp="2024-04-25T14:42:37">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/venv/lib/python3.10/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 52, in test_duplicated_reservation_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC1VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 163, in test_parametrized_cases_tests
    valor = mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC2VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 163, in test_parametrized_cases_tests
    valor = mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC3VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 163, in test_parametrized_cases_tests
    valor = mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC4VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 163, in test_parametrized_cases_tests
    valor = mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC19INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC20INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC21INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC22INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC23INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC24INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC25INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC26INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC27INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC29INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC30INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC31INVALID]" time="0.068" timestamp="2024-04-25T14:42:37">
		<error type="AttributeError" message="'PhoneNumber' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 27, in room_reservation
    my_reservation = HotelReservation(id_card=id_card,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_reservation.py", line 41, in __init__
    self.__phone_number = PhoneNumber(phone_number).value
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_phone_num.py", line 14, in __init__
    self._attr_value = self.validate(attr_value)
AttributeError: 'PhoneNumber' object has no attribute 'validate'
]]></error>
	</testcase>
</testsuite>
