<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_checkout_tests.TestDeliverProduct-20240425130549" tests="7" file="test_checkout_tests.py" time="0.060" timestamp="2024-04-25T13:05:49" failures="1" errors="0" skipped="0">
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_checkin_code_not_found_date_signature" time="0.004" timestamp="2024-04-25T13:05:49"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_checkout_ok" time="0.004" timestamp="2024-04-25T13:05:49"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_bad_date_signature" time="0.006" timestamp="2024-04-25T13:05:49"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_no_date" time="0.004" timestamp="2024-04-25T13:05:49"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_no_store_check_in" time="0.018" timestamp="2024-04-25T13:05:49"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_store_check_in_is_empty" time="0.005" timestamp="2024-04-25T13:05:49"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_already_checkout" time="0.017" timestamp="2024-04-25T13:05:49">
		<failure type="AssertionError" message="HotelManagementException not raised"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/.venv/lib/python3.9/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 90, in test_already_checkout
    my_manager.guest_checkout(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 226, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 163, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: HotelManagementException not raised
]]></failure>
	</testcase>
</testsuite>
