<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_checkout_tests.TestDeliverProduct-20240424234234" tests="7" file="test_checkout_tests.py" time="0.050" timestamp="2024-04-24T23:42:34" failures="2" errors="0" skipped="0">
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_checkin_code_not_found_date_signature" time="0.006" timestamp="2024-04-24T23:42:34"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_checkout_ok" time="0.005" timestamp="2024-04-24T23:42:34"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_bad_date_signature" time="0.005" timestamp="2024-04-24T23:42:34"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_no_date" time="0.005" timestamp="2024-04-24T23:42:34"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_store_check_in_is_empty" time="0.005" timestamp="2024-04-24T23:42:34"/>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_already_checkout" time="0.019" timestamp="2024-04-24T23:42:34">
		<failure type="AssertionError" message="HotelManagementException not raised"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/venv/lib/python3.10/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 89, in test_already_checkout
    with self.assertRaises(HotelManagementException) as context_manager:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 226, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 163, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: HotelManagementException not raised
]]></failure>
	</testcase>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_no_store_check_in" time="0.006" timestamp="2024-04-24T23:42:34">
		<failure type="AssertionError" message="'Error: room key not found' != 'Error: store checkin not found'
- Error: room key not found
+ Error: store checkin not found
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/venv/lib/python3.10/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 194, in test_guest_checkout_no_store_check_in
    self.assertEqual(context_manager.exception.message, "Error: store checkin not found")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: 'Error: room key not found' != 'Error: store checkin not found'
- Error: room key not found
+ Error: store checkin not found

]]></failure>
	</testcase>
</testsuite>
