<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_room_reservation_tests.TestHotelReservation-20240425140645" tests="33" file="test_room_reservation_tests.py" time="0.075" timestamp="2024-04-25T14:06:45" failures="0" errors="33" skipped="0">
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_duplicated_id_reservation_tests" time="0.001" timestamp="2024-04-25T14:06:45">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 98, in test_duplicated_id_reservation_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_duplicated_reservation_tests" time="0.002" timestamp="2024-04-25T14:06:45">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/venv/lib/python3.10/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 52, in test_duplicated_reservation_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC1VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 163, in test_parametrized_cases_tests
    valor = mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC2VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 163, in test_parametrized_cases_tests
    valor = mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC3VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 163, in test_parametrized_cases_tests
    valor = mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC4VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 163, in test_parametrized_cases_tests
    valor = mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC5INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC6INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC7INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC8INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC9INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC10INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute '_error_message'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 11, in __init__
    self._attr_value = self._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 15, in _validate
    super()._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute.py", line 17, in _validate
    raise HotelManagementException(self._error_message)
AttributeError: 'IDNum' object has no attribute '_error_message'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC11INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute '_error_message'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 11, in __init__
    self._attr_value = self._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 15, in _validate
    super()._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute.py", line 17, in _validate
    raise HotelManagementException(self._error_message)
AttributeError: 'IDNum' object has no attribute '_error_message'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC12INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute '_error_message'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 11, in __init__
    self._attr_value = self._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 15, in _validate
    super()._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute.py", line 17, in _validate
    raise HotelManagementException(self._error_message)
AttributeError: 'IDNum' object has no attribute '_error_message'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC13INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute '_error_message'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 11, in __init__
    self._attr_value = self._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 15, in _validate
    super()._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute.py", line 17, in _validate
    raise HotelManagementException(self._error_message)
AttributeError: 'IDNum' object has no attribute '_error_message'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC14INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute '_error_message'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 11, in __init__
    self._attr_value = self._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute_id.py", line 15, in _validate
    super()._validate(attr_value)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/attributes/attribute.py", line 17, in _validate
    raise HotelManagementException(self._error_message)
AttributeError: 'IDNum' object has no attribute '_error_message'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC15INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC16INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC17INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC18INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC19INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC20INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC21INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC22INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC23INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC24INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC25INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC26INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC27INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC28INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC29INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC30INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC31INVALID]" time="0.072" timestamp="2024-04-25T14:06:45">
		<error type="AttributeError" message="'IDNum' object has no attribute 'validate'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 199, in test_parametrized_cases_tests
    mngr.room_reservation(credit_card=credit_card_number,
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 66, in room_reservation
    arrival_date, credit_card, num_days, phone_number, room_type = self.validate_data_room_res(
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 97, in validate_data_room_res
    IDNum(id_card).validate(id_card)
AttributeError: 'IDNum' object has no attribute 'validate'
]]></error>
	</testcase>
</testsuite>
